
#ifndef __TOKENS_H__
#define __TOKENS_H__ 1

#include <stddef.h>

#define TOKENS \
  TOKEN_DEF(IDENTIFIER), \
  TOKEN_DEF(TYPE_NAME), \
  TOKEN_DEF(ENUM_CONST), \
  TOKEN_DEF(BREAK), \
  TOKEN_DEF(CASE), \
  TOKEN_DEF(CONST), \
  TOKEN_DEF(CHAR), \
  TOKEN_DEF(CONTINUE), \
  TOKEN_DEF(DEFAULT), \
  TOKEN_DEF(DO), \
  TOKEN_DEF(DOUBLE), \
  TOKEN_DEF(ELSE), \
  TOKEN_DEF(ENUM), \
  TOKEN_DEF(EXTERN), \
  TOKEN_DEF(FLOAT), \
  TOKEN_DEF(FOR), \
  TOKEN_DEF(GOTO), \
  TOKEN_DEF(IF), \
  TOKEN_DEF(INT), \
  TOKEN_DEF(LONG), \
  TOKEN_DEF(REGISTER), \
  TOKEN_DEF(VOLATILE), \
  TOKEN_DEF(RETURN), \
  TOKEN_DEF(SHORT), \
  TOKEN_DEF(SIGNED), \
  TOKEN_DEF(SIZEOF), \
  TOKEN_DEF(ALIGNOF), \
  TOKEN_DEF(STATIC), \
  TOKEN_DEF(STRUCT), \
  TOKEN_DEF(SWITCH), \
  TOKEN_DEF(TYPEDEF), \
  TOKEN_DEF(UNION), \
  TOKEN_DEF(UNSIGNED), \
  TOKEN_DEF(VOID), \
  TOKEN_DEF(WHILE), \
  TOKEN_DEF(ATTRIBUTE), \
  TOKEN_DEF(I_CONSTANT_RAW), \
  TOKEN_DEF(C_CONSTANT), \
  TOKEN_DEF(C16_CONSTANT), \
  TOKEN_DEF(I_CONSTANT), \
  TOKEN_DEF(U_CONSTANT), \
  TOKEN_DEF(L_CONSTANT), \
  TOKEN_DEF(UL_CONSTANT), \
  TOKEN_DEF(F_CONSTANT_RAW), \
  TOKEN_DEF(F_CONSTANT), \
  TOKEN_DEF(D_CONSTANT), \
  TOKEN_DEF(STRING_LITERAL), \
  TOKEN_DEF(EMPTY_STRING_LITERAL), \
  TOKEN_DEF(ELLIPSIS), \
  TOKEN_DEF(DDOT), \
  TOKEN_DEF(RIGHT_ASSIGN), \
  TOKEN_DEF(LEFT_ASSIGN), \
  TOKEN_DEF(ADD_ASSIGN), \
  TOKEN_DEF(SUB_ASSIGN), \
  TOKEN_DEF(MUL_ASSIGN), \
  TOKEN_DEF(DIV_ASSIGN), \
  TOKEN_DEF(MOD_ASSIGN), \
  TOKEN_DEF(AND_ASSIGN), \
  TOKEN_DEF(XOR_ASSIGN), \
  TOKEN_DEF(OR_ASSIGN), \
  TOKEN_DEF(RIGHT_OP), \
  TOKEN_DEF(LEFT_OP), \
  TOKEN_DEF(INC_OP), \
  TOKEN_DEF(DEC_OP), \
  TOKEN_DEF(PTR_OP), \
  TOKEN_DEF(AND_OP), \
  TOKEN_DEF(OR_OP), \
  TOKEN_DEF(LE_OP), \
  TOKEN_DEF(GE_OP), \
  TOKEN_DEF(EQ_OP), \
  TOKEN_DEF(NE_OP), \
  TOKEN_DEF(DSHARP), \
  TOKEN_DEF(DANGLING_NEWLINE), \
  TOKEN_DEF(NEWLINE), \
  TOKEN_DEF(UNTERMINATED_COMMENT), \
  TOKEN_DEF(BAD_CHARACTER)

#define TOKEN_DEF(tt) tt

enum Tokens {
  LAST_SIMPLE_TOKEN=0xff, 
 
  TOKENS,

  NUMBER_OF_TOKENS 
};


#undef TOKEN_DEF

typedef size_t YYLTYPE;
typedef int YYSTYPE;


const char* tokenName(int token);
const char* tokenNameInBuffer(int token, char* buff);

#endif // __TOKENS_H__
